database: quark_strm.db
log_level: INFO
log_file: logs/quark_strm.log
colored_log: true
timeout: 30
exts:
  - .mp4
  - .mkv
  - .avi
  - .mov
  - .flv
  - .wmv
alt_exts:
  - .srt
  - .ass
  - .ssa
create_sub_directory: false
endpoints:
  - base_url: http://localhost:5244
    token: ""
    username: ""
    password: ""
    insecure_tls_verify: false
    max_connections: 5
    dirs:
      - local_directory: ./strm
        remote_directories:
          - /video
        not_recursive: false
        create_sub_directory: false
        disabled: false
        force_refresh: false
